#!/bin/bash
set -eu
sudo -u postgres psql -d pumpstation <<'SQL'
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS mf VARCHAR(16);
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS pump_type VARCHAR(16);
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS series VARCHAR(32);
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS q_max DOUBLE PRECISION;
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS h_max DOUBLE PRECISION;
ALTER TABLE pumps ADD COLUMN IF NOT EXISTS frequency_rpm DOUBLE PRECISION;
SQL
echo "Postgres v2 columns OK"
